# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('kwh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('kwh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('watts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('kwh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RealTime',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('watts', models.IntegerField()),
            ],
        ),
    ]
