# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161224_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrow',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
