# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170226_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldestperiodrecord',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coldestperiodrecord',
            name='start_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driestperiodrecord',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driestperiodrecord',
            name='start_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='highestpressurerecord',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='highesttemperaturerecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lowestpressurerecord',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lowesttemperaturerecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='monthrow',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strongestgustrecord',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strongestwindrecord',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warmestperiodrecord',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='warmestperiodrecord',
            name='start_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wettestdayrecord',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wettestperiodrecord',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wettestperiodrecord',
            name='start_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yearrow',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
