# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170227_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayrow',
            name='max_wind_ave',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayrow',
            name='max_wind_ave_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayrow',
            name='max_wind_gust_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strongestgustrecord',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strongestwindrecord',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
