# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170304_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourrow',
            name='bad_rows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourrow',
            name='data_quality',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourrow',
            name='good_rows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
