# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170315_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='highesttemperaturerecord',
            name='lowest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lowesttemperaturerecord',
            name='highest',
            field=models.BooleanField(default=False),
        ),
    ]
