# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170327_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastestChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('temperature', models.BooleanField(default=True)),
                ('positive', models.BooleanField(default=True)),
                ('value', models.FloatField(db_index=True)),
                ('end', models.DateTimeField()),
            ],
            options={
                'ordering': ['value'],
            },
        ),
    ]
