# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_fastestchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastestchange',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
